#!/usr/bin/env python

# Copyright (C) 2022-2025 Simon Crase

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

'''Visualize data generated by md.py'''

from argparse import ArgumentParser
from os.path import basename, join, splitext
from time import time
from matplotlib import rc
from matplotlib.pyplot import figure, show
import numpy as np

def get_file_name(name,default_ext='png',seq=None):
    '''
    Used to create file names

    Parameters:
        name          Basis for file name
        default_ext   Extension if non specified
        seq           Used if there are multiple files
    '''
    base,ext = splitext(name)
    if len(ext) == 0:
        ext = default_ext
    if seq != None:
        base = f'{base}{seq}'
    qualified_name = f'{base}.{ext}'
    if ext == 'png':
        return join(args.figs,qualified_name)
    else:
        return qualified_name


def parse_arguments():
    parser = ArgumentParser(description = __doc__)
    parser.add_argument('file', help = 'Name of saved file')
    parser.add_argument('--show', action = 'store_true', help   = 'Show plot')
    parser.add_argument('-o', '--out', default = basename(splitext(__file__)[0]),help='Name of output file')
    parser.add_argument('--figs', default = './figs', help = 'Name of folder where plots are to be stored')
    return parser.parse_args()

def reload(file):
    restored = np.load(file, allow_pickle=True)
    return restored['Xs'], restored['Vs'], restored['args'], restored['seed'], restored['epoch']

def create_energies(file):
    _, Vs, _, _, epoch = reload(file)
    m,_ = Vs.shape
    Es = np.empty((m))
    for i in range(m):
        Es[i] = 0.5 * np.sum(Vs[i,:]**2)
    return Es, epoch

if __name__=='__main__':
    rc('font',**{'family':'serif','serif':['Palatino']})
    rc('text', usetex=True)
    start  = time()
    args = parse_arguments()

    Es, epoch = create_energies(args.file)

    fig = figure(figsize = (12,12))
    ax = fig.add_subplot(1,1,1)
    ax.hist(Es)
    ax.set_title(f'Epoch={epoch}')
    fig.savefig(get_file_name(args.out))

    elapsed = time() - start
    minutes = int(elapsed/60)
    seconds = elapsed - 60*minutes
    print (f'Elapsed Time {minutes} m {seconds:.2f} s')

    if args.show:
        show()
